In [1]:
# Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
# might choose one over the other.

In [2]:
## In ordinal encoding we have order or rank whereas in label encoding we have alphabetical label.
## For example: I have dataset that contain features 'size', 'haircolor', 'level of education', . 
## for size feature i will  choose ordinal and for these two i will choose label.

In [3]:
# Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
# a machine learning project.

In [4]:
## Target Guide Ordinal Encoding fisrt slect target variable and find the mean, median of target variable for convert categorical variable in the 
## numerical values.
## Example : I will use this encoding in machine learning when we have large number of uniqe value in categorical features.
# let supppose we have a dataset below:

In [8]:
import seaborn as sns
import pandas as pd
k=sns.load_dataset('iris')
df=pd.DataFrame(k)
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [10]:
k=df.groupby('species')['sepal_length'].mean().to_dict()

In [11]:
k

{'setosa': 5.006, 'versicolor': 5.936, 'virginica': 6.587999999999999}

In [13]:
df['encoded']=df['species'].map(k)

In [15]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species  encoded
0           5.1          3.5           1.4          0.2  setosa    5.006
1           4.9          3.0           1.4          0.2  setosa    5.006
2           4.7          3.2           1.3          0.2  setosa    5.006
3           4.6          3.1           1.5          0.2  setosa    5.006
4           5.0          3.6           1.4          0.2  setosa    5.006

In [16]:
# Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

In [17]:
## covarince : cov(x,y)=Summation of (xi-sample mean of x)(yi-sample mean of y)/(n-1)
# it define the relationship between x and y whether it is postive and negative due to it we can easliy predict our model.

In [18]:
# Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
# large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
# Show your code and explain the output.

In [26]:
import pandas as pd
df1=pd.DataFrame({'color':['red','green','blue'],'size':['small','medium','large'],'Material':['wood','metal','plastic']})
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
k=label.fit_transform(df1['color'])
r=label.fit_transform(df1['size'])
n=label.fit_transform(df1['Material'])

In [27]:
k

array([2, 1, 0])

In [28]:
n

array([2, 0, 1])

In [29]:
r

array([2, 1, 0])

In [30]:
# Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
# level. Interpret the results.

In [34]:
import numpy as np
age = [30, 35, 40, 45, 50]  # Example values for Age
income = [50000, 60000, 70000, 80000, 90000]  # Example values for Income
education_level = [12, 14, 16, 18, 20]  # Example values for Education Level
data=np.array([age,income,education_level])
cov_matrix=np.cov(data)

In [36]:
print(cov_matrix)

[[6.25e+01 1.25e+05 2.50e+01]
 [1.25e+05 2.50e+08 5.00e+04]
 [2.50e+01 5.00e+04 1.00e+01]]


In [37]:
# Q6. You are working on a machine learning project with a dataset containing several categorical
# variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
# and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
# each variable, and why?

In [38]:
# Gender: For the "Gender" variable, which has two categories (Male/Female), I would use Label Encoding. Since there is no inherent ordering 
# or hierarchy between the two categories, label encoding would be appropriate.It assigns the values 0 and 1 to represent Male and Female, respectively.

# Education Level: For the "Education Level" variable with multiple categories (High School/Bachelor's/Master's/PhD), I would use Ordinal Encoding.
# This encoding method captures the natural ordering or hierarchy among the categories.

# Employment Status: For the "Employment Status" variable with multiple categories (Unemployed/Part-Time/Full-Time), I would use One-Hot Encoding. 
# One-Hot Encoding is suitable when there is no inherent ordering or hierarchy among the categories, and each category is considered equally distinct.
# It creates binary columns for each category

In [39]:
# Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
# categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
# East/West). Calculate the covariance between each pair of variables and interpret the results.

In [58]:
import numpy as np

# Assuming you have the dataset with variables Temperature, Humidity, Weather Condition, and Wind Direction
temperature = [25, 30, 28, 20, 22]  # Example values for Temperature
humidity = [60, 65, 70, 75, 80]  # Example values for Humidity
weather_condition = ['Sunny', 'Cloudy', 'Cloudy', 'Rainy', 'Sunny']  # Example values for Weather Condition
wind_direction = ['North', 'South', 'East', 'West', 'North']  # Example values for Wind Direction

# Create a numpy array from the continuous variables
continuous_data = np.array([temperature, humidity])

# Calculate the covariance between the continuous variables
cov_continuous = np.cov(continuous_data)

print("Covariance between Temperature and Humidity:")
print(cov_continuous)



Covariance between Temperature and Humidity:
[[ 17.  -20. ]
 [-20.   62.5]]


In [69]:
# Create a pandas DataFrame from the categorical variables
data = pd.DataFrame({'Weather Condition': weather_condition, 'Wind Direction': wind_direction})
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
m=label.fit_transform(data['Weather Condition'])
n=label.fit_transform(data['Wind Direction'])
m1=np.array(m)
m2=np.array(n)
np.cov(m1,m2)

array([[1. , 0. ],
       [0. , 1.3]])