In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
list_ = [1,2,3,4,5 ]
array_list = np.array(object = list_)

In [4]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [11]:
# Yes, there is a difference in the data type of variables list_ and array_list. variables list_ print just a list type but array_list print n 
# dimnesional array using numpy libarary
print(type(list_))

<class 'list'>


In [12]:
print(type(array_list))

<class 'numpy.ndarray'>


In [13]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [14]:
list_

[1, 2, 3, 4, 5]

In [54]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [21]:
array_list

array([1, 2, 3, 4, 5])

In [39]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [43]:
# Q3. Considering the following changes in the variable, array_list:
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.
array_list = np.array(object = list_, dtype = int)

In [48]:
# Yes, there is a difference in the datatype of the element present in the both the variables , list_ and array_list 
# list print all the element as a list type but in array_list it take n dimensional array with the integer entry 
array_list

array([1, 2, 3, 4, 5])

In [49]:
type(array_list)

numpy.ndarray

In [50]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [51]:
type(list_)

list

In [53]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [55]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [57]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [59]:
num_array.shape #it will print shape in tuple (row, column)

(2, 3)

In [60]:
num_array.size #it will print size of ndim array (i.e row*column)

6

In [61]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [63]:
arr1=np.zeros((3,3))

In [64]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
arr1.shape

(3, 3)

In [66]:
arr1.size

9

In [67]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [69]:
arr2=np.eye(5)

In [70]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
arr2.shape

(5, 5)

In [72]:
arr2.size

25